name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:

  #Runner z sys op Ubunutu:20.04
    runs-on: ubuntu-20.04
    
    steps:
      - 
        uses: actions/checkout@v3

  #Konfiguracja Buildx-a + Docker-a
      - 
        name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

  #Instalacja QEMU     
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

  #Logowanie do Github
      - 
        name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{secrets.GH_USERNAME}}
          password: ${{secrets.GH_TOKEN}}

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DH_USERNAME}}
          password: ${{secrets.DH_TOKEN}}

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/kacperki/fibcalc
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

    #Zbudowanie obrazu i wypchanie na Dockerhub-a       
      - 
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=docker.io/kacperki/fibcalc-cache
          cache-to: type=registry,ref=docker.io/kacperki/fibcalc-cache
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          file: ./Dockerfile3
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}